In [1]:
import pandas as pd

In [2]:
# Load the thyroid cancer risk data
risk_df = pd.read_csv("../data/raw/thyroid_cancer_risk_data.csv")

risk_df.head()

,Patient_ID,Age,Gender,Country,Ethnicity,Family_History,Radiation_Exposure,Iodine_Deficiency,Smoking,Obesity,Diabetes,TSH_Level,T3_Level,T4_Level,Nodule_Size,Thyroid_Cancer_Risk,Diagnosis
0,1,66,Male,Russia,Caucasian,No,Yes,No,No,No,No,9.37,1.67,6.16,1.08,Low,Benign
1,2,29,Male,Germany,Hispanic,No,Yes,No,No,No,No,1.83,1.73,10.54,4.05,Low,Benign
2,3,86,Male,Nigeria,Caucasian,No,No,No,No,No,No,6.26,2.59,10.57,4.61,Low,Benign
3,4,75,Female,India,Asian,No,No,No,No,No,No,4.10,2.62,11.04,2.46,Medium,Benign
4,5,35,Female,Germany,African,Yes,Yes,No,No,No,No,9.10,2.11,10.71,2.11,High,Benign

In [3]:
# Load the thyroid cancer recurrence data
recurrence_df = pd.read_csv("../data/raw/recurrence_dataset.csv")

recurrence_df.head()

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,No
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,No

In [4]:
# Display the shapes of both datasets
print("Risk Dataset Shape:")
print(risk_df.shape)

print("\nRecurrence Dataset Shape:")
print(recurrence_df.shape)

Risk Dataset Shape:
(212691, 17)

Recurrence Dataset Shape:
(383, 17)

In [5]:
# Display the column names
print(risk_df.columns)

Index(['Patient_ID', 'Age', 'Gender', 'Country', 'Ethnicity', 'Family_History',
       'Radiation_Exposure', 'Iodine_Deficiency', 'Smoking', 'Obesity',
       'Diabetes', 'TSH_Level', 'T3_Level', 'T4_Level', 'Nodule_Size',
       'Thyroid_Cancer_Risk', 'Diagnosis'],
      dtype='str')

In [6]:
## Display the column names
print(recurrence_df.columns)

Index(['Age', 'Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy',
       'Thyroid Function', 'Physical Examination', 'Adenopathy', 'Pathology',
       'Focality', 'Risk', 'T', 'N', 'M', 'Stage', 'Response', 'Recurred'],
      dtype='str')

In [7]:
#Check Dataset Information
risk_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 212691 entries, 0 to 212690
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Patient_ID           212691 non-null  int64
 1   Age                  212691 non-null  int64
 2   Gender               212691 non-null  str
 3   Country              212691 non-null  str
 4   Ethnicity            212691 non-null  str
 5   Family_History       212691 non-null  str
 6   Radiation_Exposure   212691 non-null  str
 7   Iodine_Deficiency    212691 non-null  str
 8   Smoking              212691 non-null  str
 9   Obesity              212691 non-null  str
 10  Diabetes             212691 non-null  str
 11  TSH_Level            212691 non-null  float64
 12  T3_Level             212691 non-null  float64
 13  T4_Level             212691 non-null  float64
 14  Nodule_Size          212691 non-null  float64
 15  Thyroid_Cancer_Risk  212691 non-null  str
 16  Diagnosis            212691 non-null  str
dtypes: float64(4), int64(2), str(11)
memory usage: 27.6 MB

In [8]:
recurrence_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   383 non-null    int64
 1   Gender                383 non-null    str
 2   Smoking               383 non-null    str
 3   Hx Smoking            383 non-null    str
 4   Hx Radiothreapy       383 non-null    str
 5   Thyroid Function      383 non-null    str
 6   Physical Examination  383 non-null    str
 7   Adenopathy            383 non-null    str
 8   Pathology             383 non-null    str
 9   Focality              383 non-null    str
 10  Risk                  383 non-null    str
 11  T                     383 non-null    str
 12  N                     383 non-null    str
 13  M                     383 non-null    str
 14  Stage                 383 non-null    str
 15  Response              383 non-null    str
 16  Recurred              383 non-null    str
dtypes: int64(1), str(16)
memory usage: 51.0 KB

In [9]:
#Check Missing Values
risk_df.isnull().sum()

Patient_ID             0
Age                    0
Gender                 0
Country                0
Ethnicity              0
Family_History         0
Radiation_Exposure     0
Iodine_Deficiency      0
Smoking                0
Obesity                0
Diabetes               0
TSH_Level              0
T3_Level               0
T4_Level               0
Nodule_Size            0
Thyroid_Cancer_Risk    0
Diagnosis              0
dtype: int64

In [10]:
recurrence_df.isnull().sum()

Age                     0
Gender                  0
Smoking                 0
Hx Smoking              0
Hx Radiothreapy         0
Thyroid Function        0
Physical Examination    0
Adenopathy              0
Pathology               0
Focality                0
Risk                    0
T                       0
N                       0
M                       0
Stage                   0
Response                0
Recurred                0
dtype: int64

In [11]:
#Check Target Column Distribution
risk_df["Thyroid_Cancer_Risk"].value_counts()

Thyroid_Cancer_Risk
Low       108388
Medium     72400
High       31903
Name: count, dtype: int64

In [12]:
recurrence_df.columns

Index(['Age', 'Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy',
       'Thyroid Function', 'Physical Examination', 'Adenopathy', 'Pathology',
       'Focality', 'Risk', 'T', 'N', 'M', 'Stage', 'Response', 'Recurred'],
      dtype='str')